### ISSUE TITLE
Visual studio code

### ISSUE THREAD

**Issue by KuzeyinLordu** [ironcev/without-guns-for-vs-code#22]
Could you please help I could not install java in Visual sudio code

**Comment by ironcev** [comment]
Hi @KuzeyinLordu, sorry for my late answer. This "Without Guns" project dropped out of my focus completely. I hope you have found an answer to your problem in the meanwhile.

I am not a Java developer, but I see that there are plenty of Java extensions for Visual Studio Code and I guess that with these two, for example, you might get a working Java environment:

![image](https://user-images.githubusercontent.com/4142833/63444691-6350dd00-c437-11e9-91ca-5798996ec305.png)

Opening GitHub issues in non-related projects are probably not the best place to get a quick answer to your problem. If you still have this problem I would recommend posting a question on StackOverflow making sure to follow their guidelines on [how to ask a good question](https://stackoverflow.com/help/how-to-ask).

I would also consider going for some full-blown Java IDE like [Eclipse for Java Developers](http://www.eclipse.org/downloads/packages/node/46577) instead of using Visual Studio Code.

I hope this helps.

Since the question is not related to Without Guns extension, I'll close this issue.
